-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 20:54:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@
OLD_UNIQUE_CHECKS
=
@
@
UNIQUE_CHECKS,
UNIQUE_CHECKS
=
0;
SET
@
OLD_FOREIGN_KEY_CHECKS
=
@
@
FOREIGN_KEY_CHECKS,
FOREIGN_KEY_CHECKS
=
0;
SET
@
OLD_SQL_MODE
=
@
@
SQL_MODE,
SQL_MODE
=
'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb3` DEFAULT CHARACTER SET utf8;
USE
`mydb3`;

-- -----------------------------------------------------
-- Table `mydb3`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb3`.`device`
(
  `id`
  INT
  NOT
  NULL
  AUTO_INCREMENT,
  `parent_id`
  INT
  NULL,
  `brother_id`
  INT
  NOT
  NULL
  DEFAULT
  -
  1,
  `name`
  VARCHAR
(
  45
) NOT NULL,
  `model` VARCHAR
(
  45
) NOT NULL,
  `entry_time` DATETIME NOT NULL,
  `type` INT NOT NULL,
  `function_id` VARCHAR
(
  45
) NOT NULL,
  PRIMARY KEY
(
  `id`
))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb3`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb3`.`data`
(
  `id`
  INT
  NOT
  NULL
  AUTO_INCREMENT,
  `device_id`
  INT
  NOT
  NULL,
  `time`
  DATETIME
  NOT
  NULL,
  `para1_type`
  VARCHAR
(
  45
) NULL,
  `para1_value` FLOAT NULL,
  `para2_type` VARCHAR
(
  45
) NULL,
  `para2_value` FLOAT NULL,
  `para3_type` VARCHAR
(
  45
) NULL,
  `para3_value` FLOAT NULL,
  `para4_type` VARCHAR
(
  45
) NULL,
  `para4_value` FLOAT NULL,
  `para5_type` VARCHAR
(
  45
) NULL,
  `para5_value` FLOAT NULL,
  PRIMARY KEY
(
  `id`
))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb3`.`parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb3`.`parameter`
(
  `id`
  INT
  NOT
  NULL
  AUTO_INCREMENT,
  `name`
  VARCHAR
(
  45
) NOT NULL,
  `unit` VARCHAR
(
  45
) NOT NULL,
  `max` FLOAT NOT NULL,
  `min` FLOAT NOT NULL,
  PRIMARY KEY
(
  `id`
))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb3`.`user`
(
  `username`
  INT
  NOT
  NULL,
  `password`
  VARCHAR
(
  45
) NOT NULL,
  `authority` INT NULL DEFAULT 1,
  PRIMARY KEY
(
  `username`
))
  ENGINE = InnoDB;


SET
SQL_MODE
=
@
OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS
=
@
OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS
=
@
OLD_UNIQUE_CHECKS;
